export default {
    data() {
        return {
            froala_config: function () {
                const runtimeConfig = useRuntimeConfig();
                return {
                    height: 600,
                    // inlineMode: false,
                    pastePlain: false,
                    pasteDeniedTags: [],
                    pasteDeniedAttributes: [],
                    wordPasteModal: false,
                    paragraphy: false,
                    quickInsertEnabled: false,
                    toolbarButtons: [
                        "undo",
                        "redo",
                        "fullscreen",
                        "|",
                        "paragraphFormat",
                        "fontSize",
                        "textColor",
                        "backgroundColor",
                        "color",
                        "bold",
                        "italic",
                        "underline",
                        "inlineClass",
                        "subscript",
                        "superscript",
                        "|",
                        "align",
                        "outdent",
                        "indent",
                        "|",
                        "formatOL",
                        "formatUL",
                        "quote",
                        "-",
                        "insertLink",
                        "insertImage",
                        "insertVideo",
                        "insertFile",
                        "insertTable",
                        "|",
                        "insertHR",
                        "selectAll",
                        "clearFormatting",
                        "|",
                        "print",
                        "getPDF",
                        "html",
                        // "codeBeautifier",
                        "wirisEditor",
                        "wirisChemistry",
                        "fontAwesome",
                    ],
                    htmlAllowedTags: [
                        ".*",
                        "i",
                        "em",
                        "strong",
                        "a",
                        "br",
                        "ul",
                        "li",
                    ],
                    htmlAllowedAttrs: [
                        ".*",
                        "class",
                        "href",
                        "target",
                        "style",
                    ],
                    placeholderText: "",
                    attribution: false,
                    key: "",
                    disableRightClick: true,
                    imageUploadURL: `${runtimeConfig.public.apiBase}/froala/image`,
                    imageAllowedTypes: ["jpeg", "jpg", "png"],
                    fileUploadURL: `${runtimeConfig.public.apiBase}/froala/document`,
                    videoUploadURL: `${runtimeConfig.public.apiBase}/froala/video`,
                    imagePaste: false,
                    imagePasteProcess: false,
                    imageResize: true,
                    crossDomain: true,
                    pasteAllowedStyleProps: ["*"],
                    pasteAllowLocalImages: true,
                    htmlAllowComments: true,
                    htmlExecuteScripts: false,
                    fontSizeSelection: true,
                    //  : "18",
                    fontFamily: {
                        "Sarabun,sans-serif": "Sarabun",
                        "Arial,Helvetica,sans-serif": "Arial",
                        //   defaultSelection: "THSarabunNew",
                        //   list: {
                        //     "THSarabunNew,sans-serif": "TH Sarabun New",
                        //   },
                    },
                    fontDefaultSelection: "Sarabun",
                    fontSize: [
                        "8",
                        "10",
                        "12",
                        "14",
                        "16",
                        "18",
                        "20",
                        "22",
                        "24",
                        "30",
                        "36",
                        "48",
                        "60",
                        "72",
                    ],
                    tabSpaces: 4,
                };
            },
        };
    },
};
